-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsCpp where

newtype Id = Id String
  deriving (Eq, Ord, Show, Read)

data Program = PDefs [Def]
  deriving (Eq, Ord, Show, Read)

data Def
    = DFun Type Id [Arg] [Stm]
    | DFunc Type Id [Arg]
    | DUsing QConst
    | DTypDef Type Id
    | DTypDefVect Type [Type] Id
    | DDeclVar Type [Id]
  deriving (Eq, Ord, Show, Read)

data Arg
    = ADecl Type Id | AType Type | AConst Type Id | AConstType Type
  deriving (Eq, Ord, Show, Read)

data Stm
    = SExp Exp
    | SDecls Declaration
    | SInit Declaration Exp
    | SReturn Exp
    | SReturnVoid
    | SWhile Exp Stm
    | SBlock [Stm]
    | SIfElse Exp Stm Contd
    | SDoWhi Stm Exp
    | SFor Stm Exp Exp Stm
    | STypDef Type Id
  deriving (Eq, Ord, Show, Read)

data Declaration = DeclaSim Type [Id] | DeclaConst Type Id
  deriving (Eq, Ord, Show, Read)

data Contd = YesContd Stm | NoContd
  deriving (Eq, Ord, Show, Read)

data Exp
    = ECondit Exp Exp Exp
    | EExcept Exp
    | EPlusEq Exp Exp
    | EMinEq Exp Exp
    | EAss Exp Exp
    | EOr Exp Exp
    | EAnd Exp Exp
    | ENEq Exp Exp
    | EEq Exp Exp
    | EGEq Exp Exp
    | ELEq Exp Exp
    | EGt Exp Exp
    | ELt Exp Exp
    | ERShift Exp Exp
    | ELShift Exp Exp
    | EMinus Exp Exp
    | EPlus Exp Exp
    | EMod Exp Exp
    | EDiv Exp Exp
    | ETimes Exp Exp
    | EPointer Exp
    | ENegBool Exp
    | ENegInt Exp
    | EDecr Exp
    | EIncr Exp
    | EAssPointer Exp Exp
    | ERefCall Exp Exp
    | EArray Exp Exp
    | ECall Exp [Exp]
    | EPostDecr Exp
    | EPostIncr Exp
    | EQConst QConst
    | ETrue
    | EFalse
    | EString [String]
    | EChar Char
    | EInt Integer
    | EDouble Double
    | EPred Type Type
    | ETyped Exp Type
  deriving (Eq, Ord, Show, Read)

data QConst = QuConst [Elmt]
  deriving (Eq, Ord, Show, Read)

data Elmt = QCElmt Id | QCElntt Id [Type]
  deriving (Eq, Ord, Show, Read)

data Type
    = TypInt
    | TypChar
    | TypBool
    | TypVoid
    | TypDoub
    | TypQC QConst
    | TypRef Type
  deriving (Eq, Ord, Show, Read)

